[project]
name = "teperpetual-ambition-protocol"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/teperpetual-ambition-protocol/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.steperpetual-ambition-protocol]
path = "contracts/steperpetual-ambition-protocol.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
